// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIRl-C2Q3czWmsy1EfPzbmhcVl53cvNnk',
    appId: '1:32341282301:android:bf39024d6f10551b151d94',
    messagingSenderId: '32341282301',
    projectId: 'todo-ca666',
    storageBucket: 'todo-ca666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyJcnmoG0bdxSbGHC7JzD3U-Yy2K2tJ9E',
    appId: '1:32341282301:ios:e9cd31d597c0d418151d94',
    messagingSenderId: '32341282301',
    projectId: 'todo-ca666',
    storageBucket: 'todo-ca666.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyJcnmoG0bdxSbGHC7JzD3U-Yy2K2tJ9E',
    appId: '1:32341282301:ios:e9cd31d597c0d418151d94',
    messagingSenderId: '32341282301',
    projectId: 'todo-ca666',
    storageBucket: 'todo-ca666.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );
}
